version: '3'
services:
  web:
    container_name: ${CONTAINER_SITE_NAME}
    image: weather-app
    command: bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: ${SECRET_KEY_BASE}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
  networks:
    external:
      name: ${NETWORK}
