version: '3'
services:
  web:
    container_name: ${CONTAINER_SITE_NAME}
    build:
      context: .
      args:
        - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    command: bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      WEATHER_APP_DATABASE_PASSWORD: ${WEATHER_APP_DATABASE_PASSWORD}
      WEATHER_API_ACCESS_KEY: ${WEATHER_API_ACCESS_KEY}
      WEATHER_API_BASE_URL: ${WEATHER_API_BASE_URL}
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
networks:
  default:
    name: ${NETWORK}

#  docker exec -it weather-app-web bin/rails db:migrate
