version: '3'
services:
  web:
    image: weather-app
    command: bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
