version: '3'
services:
  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: ${WEATHER_APP_DATABASE_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    container_name: ${CONTAINER_SITE_NAME}
    build: .
    command: bin/rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: ${RAILS_ENV}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      WEATHER_APP_DATABASE_PASSWORD: ${WEATHER_APP_DATABASE_PASSWORD}
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
networks:
  default:
    name: ${NETWORK}